
title = 'Clever Cloud Documentation'
baseURL = ''

defaultContentLanguage = 'en'
languageCode = 'en-us'

googleAnalytics = ''

enableGitInfo = false

markup.highlight.noClasses = false

theme = 'docura'

