
title = 'Clever Cloud Documentation'
baseURL = 'https://testing-docura.cleverapps.io/'

defaultContentLanguage = 'en'
languageCode = 'en-us'

googleAnalytics = ''

enableGitInfo = false

markup.highlight.noClasses = false

theme = 'docura'

